/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.hello.cics;

import com.ibm.cics.jcicsx.CICSContext;

public class App {
    public String getGreeting() {
        return "Hello CICS!";
    }

    public static void main(String[] args) {
        CICSContext task = CICSContext.getCICSContext();

        // TODO...
        // https://www.ibm.com/docs/en/cics-ts/6.1?topic=jcicsx-examples

        System.out.println(new App().getGreeting());
    }
}
